// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34003
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PBP.TwitterHud.AcceptanceTests.Features.Dashboard
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Dashboard")]
    public partial class DashboardFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Dashboard.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Dashboard", "In order to plan, track and organize social media updates\r\nI want to be able to s" +
                    "ee all of the company\'s status updates in one place", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A request is received to see all tweets since 2 weeks ago")]
        public virtual void ARequestIsReceivedToSeeAllTweetsSince2WeeksAgo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A request is received to see all tweets since 2 weeks ago", ((string[])(null)));
#line 5
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Text",
                        "At"});
            table1.AddRow(new string[] {
                        "Oh the weather outside is frightful, but parking can be quite delightful! When yo" +
                            "u park and #PayByPhone, PayByPhone, PayByPhone, PayByPhone",
                        "2013-12-14T19:39"});
            table1.AddRow(new string[] {
                        "@socialnerdia Not yet but we\'re always looking to expand in the Lower Mainland. W" +
                            "e have a pilot project w/ NYDOT in The Bronx\'s Little Italy",
                        "2013-12-03T16:08"});
            table1.AddRow(new string[] {
                        "@Gingerbikeruk Yes, put it down as a car. If you\'re in the UK please follow @PayB" +
                            "yPhone_UK for questions and updates. Thanks for signing up!",
                        "2013-12-02T12:47"});
#line 6
 testRunner.Given("the user \'pay_by_phone\' has made the following tweets", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Text",
                        "At"});
            table2.AddRow(new string[] {
                        "@deblanda Hi ! you can address to @pay_by_phone who is managing North Amercia !",
                        "2013-12-13T00:29"});
            table2.AddRow(new string[] {
                        "PayByPhone et VINCI Park remportent le Grand Prix 2013 de la Revue des Collectivi" +
                            "tés Locales des paiements innovants",
                        "2013-12-12T13:04"});
#line 11
 testRunner.Given("the user \'PayByPhone\' has made the following tweets", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Text",
                        "At"});
            table3.AddRow(new string[] {
                        "@Madame_Claude Its poss that you entered the incorrect unit,please email help@pay" +
                            "byphone.co.uk so we can look into a refund for you. Thanks",
                        "2013-12-10T00:41"});
            table3.AddRow(new string[] {
                        "@james_coxNQE @ChelmsCouncil Apologies James however we were not aware of your is" +
                            "sue until now,we will make sure this gets picked up ASAP.",
                        "2013-12-09T06:49"});
            table3.AddRow(new string[] {
                        "@ChelmsCouncil @james_coxNQE Hi James,if you could email the team help@paybyphone" +
                            ".co.uk your query we will look into this for you asap, tx",
                        "2013-12-09T06:02"});
#line 15
 testRunner.Given("the user \'PayByPhone_UK\' has made the following tweets", ((string)(null)), table3, "Given ");
#line 20
 testRunner.When("a request is received to see all tweets since 2 weeks before \'2013-12-15T07:41\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.Then("the total number of tweets for the account \'pay_by_phone\' should be 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
 testRunner.And("the total number of tweets for the account \'PayByPhone\' should be 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("the total number of tweets for the account \'PayByPhone_UK\' should be 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "user",
                        "number of mentions"});
            table4.AddRow(new string[] {
                        "socialnerdia",
                        "1"});
            table4.AddRow(new string[] {
                        "Gingerbikeruk",
                        "1"});
            table4.AddRow(new string[] {
                        "PayByPhone_UK",
                        "1"});
#line 24
 testRunner.And("the total number of times users were mentioned for the account \'pay_by_phone\' sho" +
                    "uld be", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "user",
                        "number of mentions"});
            table5.AddRow(new string[] {
                        "deblanda",
                        "1"});
#line 29
 testRunner.And("the total number of times users were mentioned for the account \'PayByPhone\' shoul" +
                    "d be", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "user",
                        "number of mentions"});
            table6.AddRow(new string[] {
                        "Madame_Claude",
                        "1"});
            table6.AddRow(new string[] {
                        "ChelmsCouncil",
                        "2"});
            table6.AddRow(new string[] {
                        "james_coxNQE",
                        "2"});
#line 32
 testRunner.And("the total number of times users were mentioned for the account \'PayByPhone_UK\' sh" +
                    "ould be", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "user",
                        "text",
                        "at"});
            table7.AddRow(new string[] {
                        "pay_by_phone",
                        "Oh the weather outside is frightful, but parking can be quite delightful! When yo" +
                            "u park and #PayByPhone, PayByPhone, PayByPhone, PayByPhone",
                        "2013-12-14T19:39"});
            table7.AddRow(new string[] {
                        "PayByPhone",
                        "@deblanda Hi ! you can address to @pay_by_phone who is managing North Amercia !",
                        "2013-12-13T00:29"});
            table7.AddRow(new string[] {
                        "PayByPhone",
                        "PayByPhone et VINCI Park remportent le Grand Prix 2013 de la Revue des Collectivi" +
                            "tés Locales des paiements innovants",
                        "2013-12-12T13:04"});
            table7.AddRow(new string[] {
                        "PayByPhone_UK",
                        "@Madame_Claude Its poss that you entered the incorrect unit,please email help@pay" +
                            "byphone.co.uk so we can look into a refund for you. Thanks",
                        "2013-12-10T00:41"});
            table7.AddRow(new string[] {
                        "PayByPhone_UK",
                        "@james_coxNQE @ChelmsCouncil Apologies James however we were not aware of your is" +
                            "sue until now,we will make sure this gets picked up ASAP.",
                        "2013-12-09T06:49"});
            table7.AddRow(new string[] {
                        "PayByPhone_UK",
                        "@ChelmsCouncil @james_coxNQE Hi James,if you could email the team help@paybyphone" +
                            ".co.uk your query we will look into this for you asap, tx",
                        "2013-12-09T06:02"});
            table7.AddRow(new string[] {
                        "pay_by_phone",
                        "@socialnerdia Not yet but we\'re always looking to expand in the Lower Mainland. W" +
                            "e have a pilot project w/ NYDOT in The Bronx\'s Little Italy",
                        "2013-12-03T16:08"});
            table7.AddRow(new string[] {
                        "pay_by_phone",
                        "@Gingerbikeruk Yes, put it down as a car. If you\'re in the UK please follow @PayB" +
                            "yPhone_UK for questions and updates. Thanks for signing up!",
                        "2013-12-02T12:47"});
#line 37
 testRunner.And("the sorted list of tweets for all of the accounts over the period should be", ((string)(null)), table7, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
